# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baf1fa3f37ff3e7c22b5babb966ac371705c3e51ca8be412b4d03f7dc2fc20ba83d9288c9503053a5c4359e2257327655f1caa31ba08e3b3060efac8e9aae4f7

test:
  secret_key_base: 04082c0b4f70b2e00945a08782bf92510f6047c6e0378a63fecfc43120db7abddfe4402bf6498cf04b4f7a059252a91a907140b2d7ff340d9b21f6dc68822e5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
